### ISSUE TITLE
Filter profiles aren't being saved

### ISSUE THREAD

**Issue by Cheunguy** [RomainLK/ytc-filter#53] opened 2020-12-30 05:11 UTC
I'm on Chrome, 2.0.2, whenever I close my browser it seems to either delete the profile I had saved, or maybe its not saving them properly in the first place.

**Comment by RomainLK** [comment] 2020-12-30 08:28
Can you access the popout > settings? If so, here are a few things you can do to help me diagnose:

First in the archive tab, there is a storage usage indicator at the bottom. Could you copy paste it please?

Secondly, I would like to take a look into the storage. In order to do so, you open the console from the popout, then paste this snippet:

 ```javascript
chrome.storage.local.get(s => console.log(JSON.stringify(s)))
```

After, you can try to solve your issue with the Popout > Help tab > Full reset button.

**Comment by Cheunguy** [comment] 2020-12-30 08:57
Extension storage (not real time): 3632715/5242880
[Archive.txt](https://github.com/RomainLK/ytc-filter/files/5753611/Archive.txt)

**Comment by Cheunguy** [comment] 2020-12-30 09:02
Looks like the full reset solved the problem, thanks for your help!

**Comment by planetarian** [comment] 2020-12-31 00:44
having this same issue on three separate PCs in the latest stable Edge release. sometimes the plugin is able to load its data successfully, but it seems pretty random. I haven't been able to track down exact circumstances of when and why it happens.

Extension storage (not real time): 3962960/5242880

[ytcFilterStorage.txt](https://github.com/RomainLK/ytc-filter/files/5756116/ytcFilterStorage.txt)

I can actually see my filters in the JSON. But the profiles object is empty, and the filters aren't actually present in my filters page in the extension options.

**Comment by RomainLK** [comment] 2020-12-31 01:24
Edge is not officially supported in the sense, I'm not testing on it. Still I just tried and I don't have any issue having a global default which survives browser restart.

Is the storage extract you posted made after you saved a profile? Do you have any error message in the console when starting, or when you save the profile? 

The storage is the persistent data which will survive a browser restart. From your description, it sounds like you managed to create a profile, but it's not persisting properly. Ideally, a storage extract after saving a profile will allow us to ensure that it's properly saved, then you can try to see if you reproduce your problem.

**Comment by planetarian** [comment] 2020-12-31 01:31
the extract above was created after an instance of it "resetting" itself, which has happened seemingly a dozen times now since the latest update. When it "resets" like this, upon opening a stream, it displays the 'update info' dialog, all profiles I've saved are gone, and all general settings return to default.

If we look in the archive section of the JSON, we can see that my previously-saved filters are present in each video entry -- but all of the global settings/profile data are wiped.

**Comment by RomainLK** [comment] 2021-01-16 15:20
Considering that the rush of issues from 2.0.x seems to have ended, I'm closing this ticket.

**Closed by RomainLK** 2021-01-16 15:20 UTC
